### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ebgoldstein**
ok, here is some code to do the URL generation. @TomasBeuzen — its not super defensive like your code, because i am not good at writing code...  

and actually, I will wait to merge it until it looks ok to you... I can;t add you as a formal reviewer until you accept the invite to be a collaborator...

### CODE REVIEW

**Comment by TomasBeuzen** [comment]
Could we write some pseudo-code for how we think this workflow will go? Are you thinking something like:

```
station = "buxtoncoastalcam"
year = 2019
month = 11
day = 13
time = 1000

url = generate_url()
vr = VidViewer(url)
vr.save_frames()
vr.save_metadata()
```

**Comment by ebgoldstein** [comment]
yes, exactly

**Comment by TomasBeuzen** [comment]
Okay, so by construct, I don't want to instantiate the class for every single url (because I assume we'll be looping over several urls). Instead, I'm thinking of something like this:

```
vr = VidViewer()  # instantiate class just one time

### We could start a loop here where we loop over different station, year, month, day, times
vr.set_url(station, year, month, day, time)  # this creates the url and saves as an attribute to the class instance
vr.save_frames()  # this saves the frames from the video at the url
vr.save_metadata()  # this saves the metadata of the video of the url
```

If this is what you had in mind I can implement these changes, otherwise we can chat tomorrow :)

**Comment by ebgoldstein** [comment]
ok, this would work well i think

**Comment by TomasBeuzen** [comment]
Okay I just updated the script so that you can set the url based on station/time and also you can output a .csv file (that contains the url, the file name (which includes time), and the .jpg file paths for each frame) when you save frames. You can view the [demo file](https://github.com/ebgoldstein/TinyCollision/blob/with-url-gen/webcat_utils_demo.ipynb) to see the changes. Basically, it works like this now:

```
from webcat_utils import WebCAT

wc = WebCAT()  # Instantiate class
wc.generate_url("buxtoncoastalcam", 2019, 11, 13, 1000)  # set url
# do other stuff like save frames...
wc.save_frames(delta_t=600, fout_path="./", save_csv=True)
```

The bottom of the notebook has an example of looping over various station/year/month/time inputs. We can discuss further tomorrow or feel free to merge.

**Pull request merged**
